program ProjectFFT;

uses
  fastmm4,
  Forms,
  TestFFT in 'TestFFT.pas' {Form1},
  llstestunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\llstestunit.pas',
  testablasunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testablasunit.pas',
  testasa in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testasa.pas',
  testautogk in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testautogk.pas',
  testbdssunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testbdssunit.pas',
  testbdsvdunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testbdsvdunit.pas',
  testblasunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testblasunit.pas',
  testchebyshevunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testchebyshevunit.pas',
  testconvunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testconvunit.pas',
  testcorrunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testcorrunit.pas',
  testcreflunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testcreflunit.pas',
  testdensesolverunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testdensesolverunit.pas',
  testevdunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testevdunit.pas',
  testfftunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testfftunit.pas',
  testfhtunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testfhtunit.pas',
  testforestunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testforestunit.pas',
  testgammaunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testgammaunit.pas',
  testgkq in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testgkq.pas',
  testgq in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testgq.pas',
  testhblasunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testhblasunit.pas',
  testhermiteunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testhermiteunit.pas',
  testhqrndunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testhqrndunit.pas',
  testidwunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testidwunit.pas',
  testinverseupdateunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testinverseupdateunit.pas',
  testinvldltunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testinvldltunit.pas',
  testkmeansunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testkmeansunit.pas',
  testlaguerreunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testlaguerreunit.pas',
  testldaunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testldaunit.pas',
  testldltunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testldltunit.pas',
  testlegendreunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testlegendreunit.pas',
  testlinminunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testlinminunit.pas',
  testmatgenunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testmatgenunit.pas',
  testmatinvunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testmatinvunit.pas',
  testmincgunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testmincgunit.pas',
  testminlbfgsunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testminlbfgsunit.pas',
  testminlmunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testminlmunit.pas',
  testmlpeunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testmlpeunit.pas',
  testmlpunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testmlpunit.pas',
  testnearestneighborunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testnearestneighborunit.pas',
  testodesolverunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testodesolverunit.pas',
  testortfacunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testortfacunit.pas',
  testpcaunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testpcaunit.pas',
  testpolintunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testpolintunit.pas',
  testpsplineunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testpsplineunit.pas',
  testratinterpolation in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testratinterpolation.pas',
  testrcondldltunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testrcondldltunit.pas',
  testrcondunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testrcondunit.pas',
  testreflectionsunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testreflectionsunit.pas',
  testregressunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testregressunit.pas',
  testsafesolveunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testsafesolveunit.pas',
  testsblasunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testsblasunit.pas',
  testschurunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testschurunit.pas',
  testspdgevdunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testspdgevdunit.pas',
  testspline1dunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testspline1dunit.pas',
  testspline2dunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testspline2dunit.pas',
  testsstunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testsstunit.pas',
  testsvdunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testsvdunit.pas',
  testtrfacunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testtrfacunit.pas',
  testtsortunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testtsortunit.pas',
  testxblasunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\tests\testxblasunit.pas',
  ablas in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ablas.pas',
  ablasf in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ablasf.pas',
  airyf in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\airyf.pas',
  ap in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ap.pas',
  apserv in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\apserv.pas',
  autogk in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\autogk.pas',
  bdss in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\bdss.pas',
  bdsvd in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\bdsvd.pas',
  bessel in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\bessel.pas',
  betaf in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\betaf.pas',
  binomialdistr in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\binomialdistr.pas',
  blas in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\blas.pas',
  chebyshev in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\chebyshev.pas',
  chisquaredistr in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\chisquaredistr.pas',
  conv in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\conv.pas',
  corr in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\corr.pas',
  correlation in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\correlation.pas',
  correlationtests in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\correlationtests.pas',
  creflections in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\creflections.pas',
  dawson in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\dawson.pas',
  densesolver in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\densesolver.pas',
  descriptivestatistics in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\descriptivestatistics.pas',
  dforest in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\dforest.pas',
  elliptic in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\elliptic.pas',
  estnorm in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\estnorm.pas',
  evd in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\evd.pas',
  expintegrals in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\expintegrals.pas',
  fdistr in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\fdistr.pas',
  fft in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\fft.pas',
  fht in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\fht.pas',
  fresnel in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\fresnel.pas',
  ftbase in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ftbase.pas',
  gammafunc in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\gammafunc.pas',
  gkq in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\gkq.pas',
  gq in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\gq.pas',
  hblas in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\hblas.pas',
  hermite in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\hermite.pas',
  hqrnd in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\hqrnd.pas',
  hsschur in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\hsschur.pas',
  ibetaf in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ibetaf.pas',
  idwint in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\idwint.pas',
  igammaf in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\igammaf.pas',
  inverseupdate in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\inverseupdate.pas',
  jacobianelliptic in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\jacobianelliptic.pas',
  jarquebera in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\jarquebera.pas',
  kmeans in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\kmeans.pas',
  laguerre in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\laguerre.pas',
  lda in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\lda.pas',
  ldlt in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ldlt.pas',
  legendre in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\legendre.pas',
  linmin in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\linmin.pas',
  linreg in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\linreg.pas',
  logit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\logit.pas',
  lsfit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\lsfit.pas',
  mannwhitneyu in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\mannwhitneyu.pas',
  matdet in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\matdet.pas',
  matgen in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\matgen.pas',
  matinv in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\matinv.pas',
  minasa in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\minasa.pas',
  mincg in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\mincg.pas',
  minlbfgs in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\minlbfgs.pas',
  minlm in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\minlm.pas',
  mlpbase in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\mlpbase.pas',
  mlpe in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\mlpe.pas',
  mlptrain in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\mlptrain.pas',
  nearestneighbor in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\nearestneighbor.pas',
  nearunityunit in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\nearunityunit.pas',
  normaldistr in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\normaldistr.pas',
  odesolver in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\odesolver.pas',
  ortfac in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ortfac.pas',
  pca in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\pca.pas',
  poissondistr in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\poissondistr.pas',
  polint in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\polint.pas',
  psif in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\psif.pas',
  pspline in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\pspline.pas',
  ratint in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ratint.pas',
  ratinterpolation in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ratinterpolation.pas',
  rcond in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\rcond.pas',
  reflections in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\reflections.pas',
  rotations in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\rotations.pas',
  safesolve in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\safesolve.pas',
  sblas in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\sblas.pas',
  schur in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\schur.pas',
  sdet in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\sdet.pas',
  sinverse in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\sinverse.pas',
  spdgevd in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\spdgevd.pas',
  spline1d in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\spline1d.pas',
  spline2d in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\spline2d.pas',
  spline3 in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\spline3.pas',
  srcond in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\srcond.pas',
  ssolve in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\ssolve.pas',
  stest in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\stest.pas',
  studenttdistr in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\studenttdistr.pas',
  studentttests in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\studentttests.pas',
  svd in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\svd.pas',
  trfac in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\trfac.pas',
  trigintegrals in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\trigintegrals.pas',
  trlinsolve in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\trlinsolve.pas',
  tsort in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\tsort.pas',
  variancetests in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\variancetests.pas',
  wsr in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\wsr.pas',
  xblas in '..\..\sharedUtils\math\alglib-2.6.0.delphi (1)\delphi\src\xblas.pas',
  ubuffsignal in '..\..\sharedUtils\mera\ubuffsignal.pas',
  uMeraFile in '..\..\sharedUtils\mera\uMeraFile.pas',
  umeraSignal in '..\..\sharedUtils\mera\umeraSignal.pas',
  uSignalsUtils in '..\..\sharedUtils\mera\uSignalsUtils.pas',
  PerformanceTime in 'PerformanceTime.pas',
  uHardwareMath in '..\..\sharedUtils\math\uHardwareMath.pas',
  uChart in '..\..\sharedUtils\компоненты\chart_dpk\chart\uChart.pas',
  uAxis in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uAxis.pas',
  uBasePage in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uBasePage.pas',
  uBasicTrend in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uBasicTrend.pas',
  uBuffTrend in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uBuffTrend.pas',
  uBuffTrend1d in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uBuffTrend1d.pas',
  uDoubleCursor in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uDoubleCursor.pas',
  uDrawObj in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uDrawObj.pas',
  uDrawObjMng in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uDrawObjMng.pas',
  uEdit in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uEdit.pas',
  uFloatEdit in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uFloatEdit.pas',
  uFloatLabel in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uFloatLabel.pas',
  uLegend in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\uLegend.pas',
  upage in '..\..\sharedUtils\компоненты\chart_dpk\chart\items\upage.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.

