// CodeGear C++Builder
// Copyright (c) 1995, 2009 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'Jclalgorithms.pas' rev: 21.00

#ifndef JclalgorithmsHPP
#define JclalgorithmsHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member functions
#pragma pack(push,8)
#include <System.hpp>	// Pascal unit
#include <Sysinit.hpp>	// Pascal unit
#include <Jclunitversioning.hpp>	// Pascal unit
#include <Jclbase.hpp>	// Pascal unit
#include <Jclcontainerintf.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Jclalgorithms
{
//-- type declarations -------------------------------------------------------
template<typename T> class DELPHICLASS TJclAlgorithms__1;
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION TJclAlgorithms__1 : public System::TObject
{
	typedef System::TObject inherited;
	
public:
	__classmethod void __fastcall Iterate(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, int Count, _decl_TIterateProcedure__1(T, F));
	__classmethod void __fastcall Apply(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, int Count, _decl_TApplyFunction__1(T, F));
	__classmethod System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  __fastcall Find(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, int Count, const T AItem, _decl_TCompare__1(T, AComparator))/* overload */;
	__classmethod System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  __fastcall Find(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, int Count, const T AItem, _decl_TEqualityCompare__1(T, AEqualityComparator))/* overload */;
	__classmethod int __fastcall CountObject(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, int Count, const T AItem, _decl_TCompare__1(T, AComparator))/* overload */;
	__classmethod int __fastcall CountObject(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, int Count, const T AItem, _decl_TEqualityCompare__1(T, AEqualityComparator))/* overload */;
	__classmethod void __fastcall Copy(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, int Count, const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  Output);
	__classmethod void __fastcall Generate(const System::DelphiInterface<Jclcontainerintf::IJclList__1<T> >  List, int Count, const T AItem);
	__classmethod void __fastcall Fill(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, int Count, const T AItem);
	__classmethod void __fastcall Reverse(const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  First, const System::DelphiInterface<Jclcontainerintf::IJclIterator__1<T> >  Last);
	__classmethod void __fastcall QuickSort(const System::DelphiInterface<Jclcontainerintf::IJclList__1<T> >  AList, int L, int R, _decl_TCompare__1(T, AComparator));
	__classmethod void __fastcall Sort(const System::DelphiInterface<Jclcontainerintf::IJclList__1<T> >  AList, int First, int Last, _decl_TCompare__1(T, AComparator));
public:
	/* TObject.Create */ inline __fastcall TJclAlgorithms__1(void) : System::TObject() { }
	/* TObject.Destroy */ inline __fastcall virtual ~TJclAlgorithms__1(void) { }
	
};


//-- var, const, procedure ---------------------------------------------------
extern PACKAGE Jclcontainerintf::TIntfSortProc IntfSortProc;
extern PACKAGE Jclcontainerintf::TAnsiStrSortProc AnsiStrSortProc;
extern PACKAGE Jclcontainerintf::TWideStrSortProc WideStrSortProc;
extern PACKAGE Jclcontainerintf::TUnicodeStrSortProc UnicodeStrSortProc;
extern PACKAGE Jclcontainerintf::TSingleSortProc SingleSortProc;
extern PACKAGE Jclcontainerintf::TDoubleSortProc DoubleSortProc;
extern PACKAGE Jclcontainerintf::TExtendedSortProc ExtendedSortProc;
extern PACKAGE Jclcontainerintf::TIntegerSortProc IntegerSortProc;
extern PACKAGE Jclcontainerintf::TCardinalSortProc CardinalSortProc;
extern PACKAGE Jclcontainerintf::TInt64SortProc Int64SortProc;
extern PACKAGE Jclcontainerintf::TPtrSortProc PtrSortProc;
extern PACKAGE Jclcontainerintf::TSortProc SortProc;
extern PACKAGE StaticArray<System::Byte, 256> BytePermTable;
extern PACKAGE Jclunitversioning::TUnitVersionInfo UnitVersioning;
extern PACKAGE int __fastcall IntfSimpleCompare(const System::_di_IInterface Obj1, const System::_di_IInterface Obj2);
extern PACKAGE int __fastcall AnsiStrSimpleCompare(const System::AnsiString Obj1, const System::AnsiString Obj2);
extern PACKAGE int __fastcall AnsiStrSimpleCompareI(const System::AnsiString Obj1, const System::AnsiString Obj2);
extern PACKAGE int __fastcall WideStrSimpleCompare(const System::WideString Obj1, const System::WideString Obj2);
extern PACKAGE int __fastcall WideStrSimpleCompareI(const System::WideString Obj1, const System::WideString Obj2);
extern PACKAGE int __fastcall UnicodeStrSimpleCompare(const System::UnicodeString Obj1, const System::UnicodeString Obj2);
extern PACKAGE int __fastcall UnicodeStrSimpleCompareI(const System::UnicodeString Obj1, const System::UnicodeString Obj2);
extern PACKAGE int __fastcall StrSimpleCompare(const System::UnicodeString Obj1, const System::UnicodeString Obj2);
extern PACKAGE int __fastcall SingleSimpleCompare(const float Obj1, const float Obj2);
extern PACKAGE int __fastcall DoubleSimpleCompare(const double Obj1, const double Obj2);
extern PACKAGE int __fastcall ExtendedSimpleCompare(const System::Extended Obj1, const System::Extended Obj2);
extern PACKAGE int __fastcall FloatSimpleCompare(const System::Extended Obj1, const System::Extended Obj2);
extern PACKAGE int __fastcall IntegerSimpleCompare(int Obj1, int Obj2);
extern PACKAGE int __fastcall CardinalSimpleCompare(unsigned Obj1, unsigned Obj2);
extern PACKAGE int __fastcall Int64SimpleCompare(const __int64 Obj1, const __int64 Obj2);
extern PACKAGE int __fastcall PtrSimpleCompare(void * Obj1, void * Obj2);
extern PACKAGE int __fastcall SimpleCompare(System::TObject* Obj1, System::TObject* Obj2);
extern PACKAGE int __fastcall IntegerCompare(System::TObject* Obj1, System::TObject* Obj2);
extern PACKAGE bool __fastcall IntfSimpleEqualityCompare(const System::_di_IInterface Obj1, const System::_di_IInterface Obj2);
extern PACKAGE bool __fastcall AnsiStrSimpleEqualityCompare(const System::AnsiString Obj1, const System::AnsiString Obj2);
extern PACKAGE bool __fastcall AnsiStrSimpleEqualityCompareI(const System::AnsiString Obj1, const System::AnsiString Obj2);
extern PACKAGE bool __fastcall WideStrSimpleEqualityCompare(const System::WideString Obj1, const System::WideString Obj2);
extern PACKAGE bool __fastcall WideStrSimpleEqualityCompareI(const System::WideString Obj1, const System::WideString Obj2);
extern PACKAGE bool __fastcall UnicodeStrSimpleEqualityCompare(const System::UnicodeString Obj1, const System::UnicodeString Obj2);
extern PACKAGE bool __fastcall UnicodeStrSimpleEqualityCompareI(const System::UnicodeString Obj1, const System::UnicodeString Obj2);
extern PACKAGE bool __fastcall StrSimpleEqualityCompare(const System::UnicodeString Obj1, const System::UnicodeString Obj2);
extern PACKAGE bool __fastcall SingleSimpleEqualityCompare(const float Obj1, const float Obj2);
extern PACKAGE bool __fastcall DoubleSimpleEqualityCompare(const double Obj1, const double Obj2);
extern PACKAGE bool __fastcall ExtendedSimpleEqualityCompare(const System::Extended Obj1, const System::Extended Obj2);
extern PACKAGE bool __fastcall FloatSimpleEqualityCompare(const System::Extended Obj1, const System::Extended Obj2);
extern PACKAGE bool __fastcall IntegerSimpleEqualityCompare(int Obj1, int Obj2);
extern PACKAGE bool __fastcall CardinalSimpleEqualityCompare(unsigned Obj1, unsigned Obj2);
extern PACKAGE bool __fastcall Int64SimpleEqualityCompare(const __int64 Obj1, const __int64 Obj2);
extern PACKAGE bool __fastcall PtrSimpleEqualityCompare(void * Obj1, void * Obj2);
extern PACKAGE bool __fastcall SimpleEqualityCompare(System::TObject* Obj1, System::TObject* Obj2);
extern PACKAGE int __fastcall IntfSimpleHashConvert(const System::_di_IInterface AInterface);
extern PACKAGE int __fastcall AnsiStrSimpleHashConvert(const System::AnsiString AString);
extern PACKAGE int __fastcall AnsiStrSimpleHashConvertI(const System::AnsiString AString);
extern PACKAGE int __fastcall AnsiStrSimpleHashConvertU(const System::AnsiString AString);
extern PACKAGE int __fastcall AnsiStrSimpleHashConvertUI(const System::AnsiString AString);
extern PACKAGE int __fastcall WideStrSimpleHashConvert(const System::WideString AString);
extern PACKAGE int __fastcall WideStrSimpleHashConvertI(const System::WideString AString);
extern PACKAGE int __fastcall UnicodeStrSimpleHashConvert(const System::UnicodeString AString);
extern PACKAGE int __fastcall UnicodeStrSimpleHashConvertI(const System::UnicodeString AString);
extern PACKAGE int __fastcall StrSimpleHashConvert(const System::UnicodeString AString);
extern PACKAGE int __fastcall SingleSimpleHashConvert(const float AValue);
extern PACKAGE int __fastcall DoubleSimpleHashConvert(const double AValue);
extern PACKAGE int __fastcall ExtendedSimpleHashConvert(const System::Extended AValue);
extern PACKAGE int __fastcall FloatSimpleHashConvert(const System::Extended AValue);
extern PACKAGE int __fastcall IntegerSimpleHashConvert(int AValue);
extern PACKAGE int __fastcall CardinalSimpleHashConvert(unsigned AValue);
extern PACKAGE int __fastcall Int64SimpleHashConvert(const __int64 AValue);
extern PACKAGE int __fastcall PtrSimpleHashConvert(void * APtr);
extern PACKAGE int __fastcall SimpleHashConvert(System::TObject* AObject);
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynIInterfaceArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynAnsiStringArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynWideStringArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynUnicodeStringArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynSingleArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynDoubleArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynExtendedArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynIntegerArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynCardinalArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynInt64Array &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynPointerArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynObjectArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynSizeIntArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynStringArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall MoveArray(Jclbase::TDynFloatArray &List, int FromIndex, int ToIndex, int Count)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclIntfIterator First, int Count, Jclcontainerintf::TIntfIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclAnsiStrIterator First, int Count, Jclcontainerintf::TAnsiStrIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclWideStrIterator First, int Count, Jclcontainerintf::TWideStrIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, int Count, Jclcontainerintf::TUnicodeStrIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclSingleIterator First, int Count, Jclcontainerintf::TSingleIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclDoubleIterator First, int Count, Jclcontainerintf::TDoubleIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclExtendedIterator First, int Count, Jclcontainerintf::TExtendedIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclIntegerIterator First, int Count, Jclcontainerintf::TIntegerIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclCardinalIterator First, int Count, Jclcontainerintf::TCardinalIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclInt64Iterator First, int Count, Jclcontainerintf::TInt64IterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclPtrIterator First, int Count, Jclcontainerintf::TPtrIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Iterate(const Jclcontainerintf::_di_IJclIterator First, int Count, Jclcontainerintf::TIterateProcedure F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclIntfIterator First, int Count, Jclcontainerintf::TIntfApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclAnsiStrIterator First, int Count, Jclcontainerintf::TAnsiStrApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclWideStrIterator First, int Count, Jclcontainerintf::TWideStrApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, int Count, Jclcontainerintf::TUnicodeStrApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclSingleIterator First, int Count, Jclcontainerintf::TSingleApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclDoubleIterator First, int Count, Jclcontainerintf::TDoubleApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclExtendedIterator First, int Count, Jclcontainerintf::TExtendedApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclIntegerIterator First, int Count, Jclcontainerintf::TIntegerApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclCardinalIterator First, int Count, Jclcontainerintf::TCardinalApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclInt64Iterator First, int Count, Jclcontainerintf::TInt64ApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclPtrIterator First, int Count, Jclcontainerintf::TPtrApplyFunction F)/* overload */;
extern PACKAGE void __fastcall Apply(const Jclcontainerintf::_di_IJclIterator First, int Count, Jclcontainerintf::TApplyFunction F)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclIntfIterator __fastcall Find(const Jclcontainerintf::_di_IJclIntfIterator First, int Count, const System::_di_IInterface AInterface, Jclcontainerintf::TIntfCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclIntfIterator __fastcall Find(const Jclcontainerintf::_di_IJclIntfIterator First, int Count, const System::_di_IInterface AInterface, Jclcontainerintf::TIntfEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclAnsiStrIterator __fastcall Find(const Jclcontainerintf::_di_IJclAnsiStrIterator First, int Count, const System::AnsiString AString, Jclcontainerintf::TAnsiStrCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclAnsiStrIterator __fastcall Find(const Jclcontainerintf::_di_IJclAnsiStrIterator First, int Count, const System::AnsiString AString, Jclcontainerintf::TAnsiStrEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclWideStrIterator __fastcall Find(const Jclcontainerintf::_di_IJclWideStrIterator First, int Count, const System::WideString AString, Jclcontainerintf::TWideStrCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclWideStrIterator __fastcall Find(const Jclcontainerintf::_di_IJclWideStrIterator First, int Count, const System::WideString AString, Jclcontainerintf::TWideStrEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclUnicodeStrIterator __fastcall Find(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, int Count, const System::UnicodeString AString, Jclcontainerintf::TUnicodeStrCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclUnicodeStrIterator __fastcall Find(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, int Count, const System::UnicodeString AString, Jclcontainerintf::TUnicodeStrEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclSingleIterator __fastcall Find(const Jclcontainerintf::_di_IJclSingleIterator First, int Count, const float AValue, Jclcontainerintf::TSingleCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclSingleIterator __fastcall Find(const Jclcontainerintf::_di_IJclSingleIterator First, int Count, const float AValue, Jclcontainerintf::TSingleEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclDoubleIterator __fastcall Find(const Jclcontainerintf::_di_IJclDoubleIterator First, int Count, const double AValue, Jclcontainerintf::TDoubleCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclDoubleIterator __fastcall Find(const Jclcontainerintf::_di_IJclDoubleIterator First, int Count, const double AValue, Jclcontainerintf::TDoubleEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclExtendedIterator __fastcall Find(const Jclcontainerintf::_di_IJclExtendedIterator First, int Count, const System::Extended AValue, Jclcontainerintf::TExtendedCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclExtendedIterator __fastcall Find(const Jclcontainerintf::_di_IJclExtendedIterator First, int Count, const System::Extended AValue, Jclcontainerintf::TExtendedEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclIntegerIterator __fastcall Find(const Jclcontainerintf::_di_IJclIntegerIterator First, int Count, int AValue, Jclcontainerintf::TIntegerCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclIntegerIterator __fastcall Find(const Jclcontainerintf::_di_IJclIntegerIterator First, int Count, int AValue, Jclcontainerintf::TIntegerEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclCardinalIterator __fastcall Find(const Jclcontainerintf::_di_IJclCardinalIterator First, int Count, unsigned AValue, Jclcontainerintf::TCardinalCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclCardinalIterator __fastcall Find(const Jclcontainerintf::_di_IJclCardinalIterator First, int Count, unsigned AValue, Jclcontainerintf::TCardinalEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclInt64Iterator __fastcall Find(const Jclcontainerintf::_di_IJclInt64Iterator First, int Count, const __int64 AValue, Jclcontainerintf::TInt64Compare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclInt64Iterator __fastcall Find(const Jclcontainerintf::_di_IJclInt64Iterator First, int Count, const __int64 AValue, Jclcontainerintf::TInt64EqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclPtrIterator __fastcall Find(const Jclcontainerintf::_di_IJclPtrIterator First, int Count, void * APtr, Jclcontainerintf::TPtrCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclPtrIterator __fastcall Find(const Jclcontainerintf::_di_IJclPtrIterator First, int Count, void * APtr, Jclcontainerintf::TPtrEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclIterator __fastcall Find(const Jclcontainerintf::_di_IJclIterator First, int Count, System::TObject* AObject, Jclcontainerintf::TCompare AComparator)/* overload */;
extern PACKAGE Jclcontainerintf::_di_IJclIterator __fastcall Find(const Jclcontainerintf::_di_IJclIterator First, int Count, System::TObject* AObject, Jclcontainerintf::TEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclIntfIterator First, int Count, const System::_di_IInterface AInterface, Jclcontainerintf::TIntfCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclIntfIterator First, int Count, const System::_di_IInterface AInterface, Jclcontainerintf::TIntfEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclAnsiStrIterator First, int Count, const System::AnsiString AString, Jclcontainerintf::TAnsiStrCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclAnsiStrIterator First, int Count, const System::AnsiString AString, Jclcontainerintf::TAnsiStrEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclWideStrIterator First, int Count, const System::WideString AString, Jclcontainerintf::TWideStrCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclWideStrIterator First, int Count, const System::WideString AString, Jclcontainerintf::TWideStrEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, int Count, const System::UnicodeString AString, Jclcontainerintf::TUnicodeStrCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, int Count, const System::UnicodeString AString, Jclcontainerintf::TUnicodeStrEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclSingleIterator First, int Count, const float AValue, Jclcontainerintf::TSingleCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclSingleIterator First, int Count, const float AValue, Jclcontainerintf::TSingleEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclDoubleIterator First, int Count, const double AValue, Jclcontainerintf::TDoubleCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclDoubleIterator First, int Count, const double AValue, Jclcontainerintf::TDoubleEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclExtendedIterator First, int Count, const System::Extended AValue, Jclcontainerintf::TExtendedCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclExtendedIterator First, int Count, const System::Extended AValue, Jclcontainerintf::TExtendedEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclIntegerIterator First, int Count, int AValue, Jclcontainerintf::TIntegerCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclIntegerIterator First, int Count, int AValue, Jclcontainerintf::TIntegerEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclCardinalIterator First, int Count, unsigned AValue, Jclcontainerintf::TCardinalCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclCardinalIterator First, int Count, unsigned AValue, Jclcontainerintf::TCardinalEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclInt64Iterator First, int Count, const __int64 AValue, Jclcontainerintf::TInt64Compare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclInt64Iterator First, int Count, const __int64 AValue, Jclcontainerintf::TInt64EqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclPtrIterator First, int Count, void * APtr, Jclcontainerintf::TPtrCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclPtrIterator First, int Count, void * APtr, Jclcontainerintf::TPtrEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclIterator First, int Count, System::TObject* AObject, Jclcontainerintf::TCompare AComparator)/* overload */;
extern PACKAGE int __fastcall CountObject(const Jclcontainerintf::_di_IJclIterator First, int Count, System::TObject* AObject, Jclcontainerintf::TEqualityCompare AEqualityComparator)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclIntfIterator First, int Count, const Jclcontainerintf::_di_IJclIntfIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclAnsiStrIterator First, int Count, const Jclcontainerintf::_di_IJclAnsiStrIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclWideStrIterator First, int Count, const Jclcontainerintf::_di_IJclWideStrIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, int Count, const Jclcontainerintf::_di_IJclUnicodeStrIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclSingleIterator First, int Count, const Jclcontainerintf::_di_IJclSingleIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclDoubleIterator First, int Count, const Jclcontainerintf::_di_IJclDoubleIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclExtendedIterator First, int Count, const Jclcontainerintf::_di_IJclExtendedIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclIntegerIterator First, int Count, const Jclcontainerintf::_di_IJclIntegerIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclCardinalIterator First, int Count, const Jclcontainerintf::_di_IJclCardinalIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclInt64Iterator First, int Count, const Jclcontainerintf::_di_IJclInt64Iterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclPtrIterator First, int Count, const Jclcontainerintf::_di_IJclPtrIterator Output)/* overload */;
extern PACKAGE void __fastcall Copy(const Jclcontainerintf::_di_IJclIterator First, int Count, const Jclcontainerintf::_di_IJclIterator Output)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclIntfList List, int Count, const System::_di_IInterface AInterface)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclAnsiStrList List, int Count, const System::AnsiString AString)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclWideStrList List, int Count, const System::WideString AString)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclUnicodeStrList List, int Count, const System::UnicodeString AString)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclSingleList List, int Count, const float AValue)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclDoubleList List, int Count, const double AValue)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclExtendedList List, int Count, const System::Extended AValue)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclIntegerList List, int Count, int AValue)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclCardinalList List, int Count, unsigned AValue)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclInt64List List, int Count, const __int64 AValue)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclPtrList List, int Count, void * APtr)/* overload */;
extern PACKAGE void __fastcall Generate(const Jclcontainerintf::_di_IJclList List, int Count, System::TObject* AObject)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclIntfIterator First, int Count, const System::_di_IInterface AInterface)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclAnsiStrIterator First, int Count, const System::AnsiString AString)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclWideStrIterator First, int Count, const System::WideString AString)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, int Count, const System::UnicodeString AString)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclSingleIterator First, int Count, const float AValue)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclDoubleIterator First, int Count, const double AValue)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclExtendedIterator First, int Count, const System::Extended AValue)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclIntegerIterator First, int Count, int AValue)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclCardinalIterator First, int Count, unsigned AValue)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclInt64Iterator First, int Count, const __int64 AValue)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclPtrIterator First, int Count, void * APtr)/* overload */;
extern PACKAGE void __fastcall Fill(const Jclcontainerintf::_di_IJclIterator First, int Count, System::TObject* AObject)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclIntfIterator First, const Jclcontainerintf::_di_IJclIntfIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclAnsiStrIterator First, const Jclcontainerintf::_di_IJclAnsiStrIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclWideStrIterator First, const Jclcontainerintf::_di_IJclWideStrIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclUnicodeStrIterator First, const Jclcontainerintf::_di_IJclUnicodeStrIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclSingleIterator First, const Jclcontainerintf::_di_IJclSingleIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclDoubleIterator First, const Jclcontainerintf::_di_IJclDoubleIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclExtendedIterator First, const Jclcontainerintf::_di_IJclExtendedIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclIntegerIterator First, const Jclcontainerintf::_di_IJclIntegerIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclCardinalIterator First, const Jclcontainerintf::_di_IJclCardinalIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclInt64Iterator First, const Jclcontainerintf::_di_IJclInt64Iterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclPtrIterator First, const Jclcontainerintf::_di_IJclPtrIterator Last)/* overload */;
extern PACKAGE void __fastcall Reverse(const Jclcontainerintf::_di_IJclIterator First, const Jclcontainerintf::_di_IJclIterator Last)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclIntfList AList, int L, int R, Jclcontainerintf::TIntfCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclAnsiStrList AList, int L, int R, Jclcontainerintf::TAnsiStrCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclWideStrList AList, int L, int R, Jclcontainerintf::TWideStrCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclUnicodeStrList AList, int L, int R, Jclcontainerintf::TUnicodeStrCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclSingleList AList, int L, int R, Jclcontainerintf::TSingleCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclDoubleList AList, int L, int R, Jclcontainerintf::TDoubleCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclExtendedList AList, int L, int R, Jclcontainerintf::TExtendedCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclIntegerList AList, int L, int R, Jclcontainerintf::TIntegerCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclCardinalList AList, int L, int R, Jclcontainerintf::TCardinalCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclInt64List AList, int L, int R, Jclcontainerintf::TInt64Compare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclPtrList AList, int L, int R, Jclcontainerintf::TPtrCompare AComparator)/* overload */;
extern PACKAGE void __fastcall QuickSort(const Jclcontainerintf::_di_IJclList AList, int L, int R, Jclcontainerintf::TCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclIntfList AList, int First, int Last, Jclcontainerintf::TIntfCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclAnsiStrList AList, int First, int Last, Jclcontainerintf::TAnsiStrCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclWideStrList AList, int First, int Last, Jclcontainerintf::TWideStrCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclUnicodeStrList AList, int First, int Last, Jclcontainerintf::TUnicodeStrCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclSingleList AList, int First, int Last, Jclcontainerintf::TSingleCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclDoubleList AList, int First, int Last, Jclcontainerintf::TDoubleCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclExtendedList AList, int First, int Last, Jclcontainerintf::TExtendedCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclIntegerList AList, int First, int Last, Jclcontainerintf::TIntegerCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclCardinalList AList, int First, int Last, Jclcontainerintf::TCardinalCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclInt64List AList, int First, int Last, Jclcontainerintf::TInt64Compare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclPtrList AList, int First, int Last, Jclcontainerintf::TPtrCompare AComparator)/* overload */;
extern PACKAGE void __fastcall Sort(const Jclcontainerintf::_di_IJclList AList, int First, int Last, Jclcontainerintf::TCompare AComparator)/* overload */;

}	/* namespace Jclalgorithms */
using namespace Jclalgorithms;
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// JclalgorithmsHPP
