[Application]
DefaultProjectConfigDir=projects/default
TimeSource=PC
AllowMultipleInstances=False

[Plugins]
; Plugin list will be added later.

[SQLdbConnection]
Backend=firebird
RootDirectory=/var/opt/mera/SQLdb
Database=/var/opt/mera/SQLdb/recorderlnx.fdb
Host=192.168.9.66
Port=3050
TlsRequired=0
