object ObjFrm3d: TObjFrm3d
  Left = 0
  Top = 0
  Caption = 'GLFrm'
  ClientHeight = 431
  ClientWidth = 727
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object BotSplitter: TSplitter
    Left = 0
    Top = 260
    Width = 727
    Height = 4
    Cursor = crVSplit
    Align = alBottom
    Color = clBackground
    ParentColor = False
  end
  object ToolsGB: TGroupBox
    Left = 0
    Top = 264
    Width = 727
    Height = 167
    Align = alBottom
    Caption = 'ToolsGB'
    TabOrder = 0
    object ErrorEdit: TEdit
      Left = 2
      Top = 144
      Width = 723
      Height = 21
      Margins.Left = 2
      Margins.Top = 2
      Margins.Right = 2
      Margins.Bottom = 2
      Align = alBottom
      TabOrder = 0
    end
  end
  object GL: cBaseGlComponent
    Left = 0
    Top = 0
    Width = 727
    Height = 260
    Align = alClient
    DockSite = True
    TabOrder = 1
    ShowTrasforms = True
    ExplicitLeft = 152
    ExplicitTop = 58
    ExplicitWidth = 200
    ExplicitHeight = 200
    object RightSplitter: TSplitter
      Left = 538
      Top = 1
      Height = 258
      Align = alRight
      ExplicitLeft = 496
      ExplicitTop = 144
      ExplicitHeight = 100
    end
    object RightGB: TGroupBox
      Left = 541
      Top = 1
      Width = 185
      Height = 258
      Align = alRight
      Caption = 'RightGB'
      TabOrder = 0
      ExplicitLeft = 416
      ExplicitTop = 112
      ExplicitHeight = 105
    end
  end
end
